### ISSUE TITLE
GraphQL parsing issues on Windows - minor diffs to fix provided

### ISSUE THREAD

**Issue by autcrock** [higherkindness/mu-haskell#317]
See the Discussions tab item "Building on WIndows".  Minor diffs are provided there.

Cheers

Mike Thomas

**Comment by serras** [comment]
Unfortunately, for parsing we depend on the [`graphql` library](https://hackage.haskell.org/package/graphql). I'm keeping this open to check whether in the latest version of the library the problem has been solved.

**Comment by serras** [comment]
I've just pushed a new version 0.5.0.3 of `mu-graphql` which uses an updated parser. @autcrock if would be great if you could check whether your example now works. I'm closing the issue, but if it fails, feel free to re-open.

**Comment by autcrock** [comment]
Thanks Alejandro, I'll try it out and let you know if it doesn't work this
weekend.

By the way I thought this project was very interesting. I started
implementing a project with it about the time I reported this bug, got
stuck, got a new job which has tied up my time since then and thought that
muhaskell may have been abandoned.

Glad to see you guys are still on it!

**Comment by rynoV** [comment]
Hello, just following up that the issue still seems to be present on the latest commit: `d1fbfeebdf9437e3f166782c697d03d70469b5f6`.

Maybe I'm misunderstanding, but would it be possible to just make the changes described by @autcrock [here](https://github.com/higherkindness/mu-haskell/discussions/316#discussioncomment-843966)? In particular I think we're running into the embedded characters issue.

**Comment by autcrock** [comment]
Hi Calum, Yes I second your result.  I followed up as mentioned above, got
the same result you've reported above and then got swept away by long term
health problems in my family so did not get back to Alejandro.  Overall the
best fix would be to nail, report or sort out the issue in or under the
GraphQL library.

Cheers

**Comment by rynoV** [comment]
FYI, this commit in my fork fixed the issue for me: https://github.com/rynoV/mu-haskell/commit/149ce89bdf7ad9394e025eadb8cda5f87218a293, let me know if you want me to open a PR
